#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Apr 23 02:30:12 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.StatusBar = self.CreateStatusBar(1, 0)
        self.label_1 = wx.StaticText(self, -1, "Chrome Extention Patcher\n\nTweetDeck RTL", style=wx.ALIGN_CENTRE)
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.NullBitmap)
        self.panel_2 = wx.Panel(self, -1)
        self.button_1 = wx.Button(self, -1, "Select Chrome's extension folder")
        self.TXTInput = wx.TextCtrl(self, -1, "/home/guy/.config/google-chrome/Default/Extensions/")
        self.panel_3 = wx.Panel(self, -1)
        self.label_2 = wx.StaticText(self, -1, "Status:")
        self.LBLStatus = wx.StaticText(self, -1, "Ready")
        self.panel_1 = wx.Panel(self, -1)
        self.button_3 = wx.Button(self, -1, "Patch")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.Select_input, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.CMDcommit, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Chrome Extension Modifier")
        self.SetSize((736, 359))
        self.StatusBar.SetStatusWidths([-1])
        # statusbar fields
        StatusBar_fields = ["Welcome! Select the Chrome's extention folder in your system, and the press the 'patch' button"]
        for i in range(len(StatusBar_fields)):
            self.StatusBar.SetStatusText(StatusBar_fields[i], i)
        self.label_1.SetFont(wx.Font(16, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.TXTInput.SetMinSize((400, 27))
        self.LBLStatus.SetMinSize((300, 27))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        Sizer = wx.FlexGridSizer(3, 3, 0, 0)
        Sizer.Add(self.label_1, 0, wx.EXPAND, 0)
        Sizer.Add(self.bitmap_1, 0, wx.ALIGN_RIGHT, 0)
        Sizer.Add(self.panel_2, 1, wx.EXPAND, 0)
        Sizer.Add(self.button_1, 0, 0, 0)
        Sizer.Add(self.TXTInput, 0, 0, 0)
        Sizer.Add(self.panel_3, 1, wx.EXPAND, 0)
        Sizer.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        Sizer.Add(self.LBLStatus, 0, wx.EXPAND, 0)
        Sizer.Add(self.panel_1, 1, wx.EXPAND, 0)
        Sizer.Add(self.button_3, 0, 0, 0)
        self.SetSizer(Sizer)
        Sizer.AddGrowableRow(0)
        Sizer.AddGrowableRow(1)
        Sizer.AddGrowableRow(2)
        Sizer.AddGrowableCol(0)
        Sizer.AddGrowableCol(1)
        Sizer.AddGrowableCol(2)
        self.Layout()
        # end wxGlade

    def Select_input(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `Select_input' not implemented!"
        event.Skip()

    def CMDcommit(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `CMDcommit' not implemented!"
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame = MyFrame(None, -1, "")
    app.SetTopWindow(frame)
    frame.Show()
    app.MainLoop()
